# bash scripts/serve_models.sh scripts/config/5090x4_7b.yaml
# bash scripts/serve_models.sh scripts/config/5090x4_7b.yaml --stop
# bash scripts/serve_models.sh scripts/config/5090x4_7b.yaml --status


controller:
  host: 0.0.0.0
  port: 21001
  worker_base_port: 10081

reward_models:
  - path: /home/xingyu/pub/Skywork-o1-Open-PRM-Qwen-2.5-7B
    gpu: 0
    gpu_memory_utilization: 0.55
    max_model_length: 4096
    swap_space: 16
    
policy_models:
  - path: /home/xingyu/pub/policy_models/Qwen3-0.6B
    gpu: 3
    gpu_memory_utilization: 0.15
    max_model_length: 4096
    swap_space: 16
  - path: /home/xingyu/pub/policy_models/Qwen3-4B
    gpu: 1
    gpu_memory_utilization: 0.30
    max_model_length: 4096
    swap_space: 16
  - path: /home/xingyu/pub/policy_models/Qwen3-1.7B
    gpu: 2
    gpu_memory_utilization: 0.2
    max_model_length: 4096
    swap_space: 16
  - path: /home/xingyu/pub/policy_models/Qwen3-8B
    gpu: 1
    gpu_memory_utilization: 0.55
    max_model_length: 4096
    swap_space: 16
  - path: /home/xingyu/pub/policy_models/Qwen3-14B
    gpu: [2,3]
    gpu_memory_utilization: 0.60
    max_model_length: 4096
    swap_space: 16

defaults:
  python: ~/miniconda3/envs/tts/bin/python
  session_prefix: tts
  max_model_length: 4096
  swap_space: 16